DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS communities;
DROP TABLE IF EXISTS signup;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS friends_request;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS login;