// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: admin.sql

package db

import (
	"context"
)

const addAdmin = `-- name: AddAdmin :one
INSERT INTO content_admin (
    content_id,
    admin
) VALUES ( $1, $2 )
RETURNING id, content_id, admin
`

type AddAdminParams struct {
	ContentID int64  `json:"content_id"`
	Admin     string `json:"admin"`
}

func (q *Queries) AddAdmin(ctx context.Context, arg AddAdminParams) (ContentAdmin, error) {
	row := q.db.QueryRowContext(ctx, addAdmin, arg.ContentID, arg.Admin)
	var i ContentAdmin
	err := row.Scan(&i.ID, &i.ContentID, &i.Admin)
	return i, err
}

const getAdmin = `-- name: GetAdmin :many
SELECT id, content_id, admin FROM content_admin
WHERE content_id=$1
`

func (q *Queries) GetAdmin(ctx context.Context, contentID int64) ([]ContentAdmin, error) {
	rows, err := q.db.QueryContext(ctx, getAdmin, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentAdmin
	for rows.Next() {
		var i ContentAdmin
		if err := rows.Scan(&i.ID, &i.ContentID, &i.Admin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
