// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: club.sql

package db

import (
	"context"
	"time"
)

const createClub = `-- name: CreateClub :one
INSERT INTO "club" (
    club_name,
    avatar_url,
    sport,
    owner,
    created_at
) VALUES (
    $1, $2, $3, $4, CURRENT_TIMESTAMP
) RETURNING id, club_name, avatar_url, sport, owner, created_at
`

type CreateClubParams struct {
	ClubName  string `json:"club_name"`
	AvatarUrl string `json:"avatar_url"`
	Sport     string `json:"sport"`
	Owner     string `json:"owner"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRowContext(ctx, createClub,
		arg.ClubName,
		arg.AvatarUrl,
		arg.Sport,
		arg.Owner,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.ClubName,
		&i.AvatarUrl,
		&i.Sport,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const getClub = `-- name: GetClub :one
SELECT id, club_name, avatar_url, sport, owner, created_at FROM "club"
WHERE id=$1
`

func (q *Queries) GetClub(ctx context.Context, id int64) (Club, error) {
	row := q.db.QueryRowContext(ctx, getClub, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.ClubName,
		&i.AvatarUrl,
		&i.Sport,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const getClubs = `-- name: GetClubs :many
SELECT id, club_name, avatar_url, sport, owner, created_at FROM "club"
`

func (q *Queries) GetClubs(ctx context.Context) ([]Club, error) {
	rows, err := q.db.QueryContext(ctx, getClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Club
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.ClubName,
			&i.AvatarUrl,
			&i.Sport,
			&i.Owner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClubsBySport = `-- name: GetClubsBySport :many
SELECT id, club_name, avatar_url, sport, owner, created_at FROM "club"
WHERE sport=$1
`

func (q *Queries) GetClubsBySport(ctx context.Context, sport string) ([]Club, error) {
	rows, err := q.db.QueryContext(ctx, getClubsBySport, sport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Club
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.ClubName,
			&i.AvatarUrl,
			&i.Sport,
			&i.Owner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchByClubName = `-- name: GetMatchByClubName :many
SELECT t.tournament_id, t.tournament_name, tm.match_id, tm.team1_id, tm.team2_id, c1.club_name AS team1_name, c2.club_name AS team2_name, tm.start_time, tm.end_time, tm.date_on, tm.sports
FROM tournament_match tm
JOIN tournament t ON tm.tournament_id = t.tournament_id
JOIN club c1 ON tm.team1_id = c1.id
JOIN club c2 ON tm.team2_id = c2.id
WHERE c1.id=$1 OR c2.id=$1
ORDER BY tm.match_id DESC, tm.start_time DESC
`

type GetMatchByClubNameRow struct {
	TournamentID   int64     `json:"tournament_id"`
	TournamentName string    `json:"tournament_name"`
	MatchID        int64     `json:"match_id"`
	Team1ID        int64     `json:"team1_id"`
	Team2ID        int64     `json:"team2_id"`
	Team1Name      string    `json:"team1_name"`
	Team2Name      string    `json:"team2_name"`
	StartTime      time.Time `json:"start_time"`
	EndTime        time.Time `json:"end_time"`
	DateOn         time.Time `json:"date_on"`
	Sports         string    `json:"sports"`
}

func (q *Queries) GetMatchByClubName(ctx context.Context, id int64) ([]GetMatchByClubNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getMatchByClubName, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchByClubNameRow
	for rows.Next() {
		var i GetMatchByClubNameRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.TournamentName,
			&i.MatchID,
			&i.Team1ID,
			&i.Team2ID,
			&i.Team1Name,
			&i.Team2Name,
			&i.StartTime,
			&i.EndTime,
			&i.DateOn,
			&i.Sports,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournamentsByClub = `-- name: GetTournamentsByClub :many
SELECT t.tournament_id, t.tournament_name, t.format, t.sport_type , t.tournament_id from tournament t
JOIN tournament_team tt ON t.tournament_id=tt.tournament_id
JOIN club c ON tt.team_id=c.id
WHERE c.club_name=$1
`

type GetTournamentsByClubRow struct {
	TournamentID   int64  `json:"tournament_id"`
	TournamentName string `json:"tournament_name"`
	Format         string `json:"format"`
	SportType      string `json:"sport_type"`
	TournamentID_2 int64  `json:"tournament_id_2"`
}

func (q *Queries) GetTournamentsByClub(ctx context.Context, clubName string) ([]GetTournamentsByClubRow, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentsByClub, clubName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTournamentsByClubRow
	for rows.Next() {
		var i GetTournamentsByClubRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.TournamentName,
			&i.Format,
			&i.SportType,
			&i.TournamentID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeam = `-- name: SearchTeam :many
SELECT id, club_name from club
WHERE club_name LIKE $1
`

type SearchTeamRow struct {
	ID       int64  `json:"id"`
	ClubName string `json:"club_name"`
}

func (q *Queries) SearchTeam(ctx context.Context, clubName string) ([]SearchTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTeam, clubName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTeamRow
	for rows.Next() {
		var i SearchTeamRow
		if err := rows.Scan(&i.ID, &i.ClubName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvatarUrl = `-- name: UpdateAvatarUrl :one
UPDATE club
SET avatar_url=$1
WHERE club_name=$2
RETURNING id, club_name, avatar_url, sport, owner, created_at
`

type UpdateAvatarUrlParams struct {
	AvatarUrl string `json:"avatar_url"`
	ClubName  string `json:"club_name"`
}

func (q *Queries) UpdateAvatarUrl(ctx context.Context, arg UpdateAvatarUrlParams) (Club, error) {
	row := q.db.QueryRowContext(ctx, updateAvatarUrl, arg.AvatarUrl, arg.ClubName)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.ClubName,
		&i.AvatarUrl,
		&i.Sport,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const updateClubName = `-- name: UpdateClubName :one
UPDATE club
SET club_name=$1
WHERE club_name=$2
RETURNING id, club_name, avatar_url, sport, owner, created_at
`

type UpdateClubNameParams struct {
	ClubName   string `json:"club_name"`
	ClubName_2 string `json:"club_name_2"`
}

func (q *Queries) UpdateClubName(ctx context.Context, arg UpdateClubNameParams) (Club, error) {
	row := q.db.QueryRowContext(ctx, updateClubName, arg.ClubName, arg.ClubName_2)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.ClubName,
		&i.AvatarUrl,
		&i.Sport,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const updateClubSport = `-- name: UpdateClubSport :one
UPDATE club
SET sport=$1
WHERE club_name=$2
RETURNING id, club_name, avatar_url, sport, owner, created_at
`

type UpdateClubSportParams struct {
	Sport    string `json:"sport"`
	ClubName string `json:"club_name"`
}

func (q *Queries) UpdateClubSport(ctx context.Context, arg UpdateClubSportParams) (Club, error) {
	row := q.db.QueryRowContext(ctx, updateClubSport, arg.Sport, arg.ClubName)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.ClubName,
		&i.AvatarUrl,
		&i.Sport,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}
