// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: communities.sql

package db

import (
	"context"
)

const createCommunity = `-- name: CreateCommunity :one
INSERT INTO communities (
    owner,
    communities_name,
    description,
    community_type
) VALUES (
    $1, $2, $3, $4
) RETURNING id, owner, communities_name, description, community_type, created_at
`

type CreateCommunityParams struct {
	Owner           string `json:"owner"`
	CommunitiesName string `json:"communities_name"`
	Description     string `json:"description"`
	CommunityType   string `json:"community_type"`
}

func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error) {
	row := q.db.QueryRowContext(ctx, createCommunity,
		arg.Owner,
		arg.CommunitiesName,
		arg.Description,
		arg.CommunityType,
	)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CommunitiesName,
		&i.Description,
		&i.CommunityType,
		&i.CreatedAt,
	)
	return i, err
}

const getAllCommunities = `-- name: GetAllCommunities :many
SELECT id, owner, communities_name, description, community_type, created_at FROM communities
ORDER BY id
`

func (q *Queries) GetAllCommunities(ctx context.Context) ([]Community, error) {
	rows, err := q.db.QueryContext(ctx, getAllCommunities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Community
	for rows.Next() {
		var i Community
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.CommunitiesName,
			&i.Description,
			&i.CommunityType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommunitiesMember = `-- name: GetCommunitiesMember :many
SELECT DISTINCT users.username FROM users
JOIN communities ON users.username = communities.owner
WHERE communities.communities_name=$1
`

func (q *Queries) GetCommunitiesMember(ctx context.Context, communitiesName string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCommunitiesMember, communitiesName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommunity = `-- name: GetCommunity :one
SELECT id, owner, communities_name, description, community_type, created_at FROM communities
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCommunity(ctx context.Context, id int64) (Community, error) {
	row := q.db.QueryRowContext(ctx, getCommunity, id)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CommunitiesName,
		&i.Description,
		&i.CommunityType,
		&i.CreatedAt,
	)
	return i, err
}
