// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: cricket_toss.sql

package db

import (
	"context"
)

const addCricketToss = `-- name: AddCricketToss :one
INSERT INTO cricket_toss (
    match_id,
    toss_decision,
    toss_win
) VALUES ($1, $2, $3)
RETURNING id, match_id, toss_decision, toss_win
`

type AddCricketTossParams struct {
	MatchID      int64  `json:"match_id"`
	TossDecision string `json:"toss_decision"`
	TossWin      int64  `json:"toss_win"`
}

func (q *Queries) AddCricketToss(ctx context.Context, arg AddCricketTossParams) (CricketToss, error) {
	row := q.db.QueryRowContext(ctx, addCricketToss, arg.MatchID, arg.TossDecision, arg.TossWin)
	var i CricketToss
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TossDecision,
		&i.TossWin,
	)
	return i, err
}

const getCricketToss = `-- name: GetCricketToss :one
SELECT id, match_id, toss_decision, toss_win FROM cricket_toss
WHERE match_id=$1
`

func (q *Queries) GetCricketToss(ctx context.Context, matchID int64) (CricketToss, error) {
	row := q.db.QueryRowContext(ctx, getCricketToss, matchID)
	var i CricketToss
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TossDecision,
		&i.TossWin,
	)
	return i, err
}
