// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: cricket_player_score.sql

package db

import (
	"context"
)

const addCricketBall = `-- name: AddCricketBall :one
INSERT INTO balls (
    match_id,
    team_id,
    bowler_id,
    ball,
    runs,
    wickets,
    wide,
    no_ball
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, match_id, bowler_id, ball, runs, wickets, wide, no_ball
`

type AddCricketBallParams struct {
	MatchID  int64 `json:"match_id"`
	TeamID   int64 `json:"team_id"`
	BowlerID int64 `json:"bowler_id"`
	Ball     int32 `json:"ball"`
	Runs     int32 `json:"runs"`
	Wickets  int32 `json:"wickets"`
	Wide     int32 `json:"wide"`
	NoBall   int32 `json:"no_ball"`
}

func (q *Queries) AddCricketBall(ctx context.Context, arg AddCricketBallParams) (Ball, error) {
	row := q.db.QueryRowContext(ctx, addCricketBall,
		arg.MatchID,
		arg.TeamID,
		arg.BowlerID,
		arg.Ball,
		arg.Runs,
		arg.Wickets,
		arg.Wide,
		arg.NoBall,
	)
	var i Ball
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MatchID,
		&i.BowlerID,
		&i.Ball,
		&i.Runs,
		&i.Wickets,
		&i.Wide,
		&i.NoBall,
	)
	return i, err
}

const addCricketBatsScore = `-- name: AddCricketBatsScore :one
INSERT INTO bats (
    batsman_id,
    match_id,
    team_id,
    position,
    runs_scored,
    balls_faced,
    fours,
    sixes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, batsman_id, team_id, match_id, position, runs_scored, balls_faced, fours, sixes
`

type AddCricketBatsScoreParams struct {
	BatsmanID  int64 `json:"batsman_id"`
	MatchID    int64 `json:"match_id"`
	TeamID     int64 `json:"team_id"`
	Position   int32 `json:"position"`
	RunsScored int32 `json:"runs_scored"`
	BallsFaced int32 `json:"balls_faced"`
	Fours      int32 `json:"fours"`
	Sixes      int32 `json:"sixes"`
}

func (q *Queries) AddCricketBatsScore(ctx context.Context, arg AddCricketBatsScoreParams) (Bat, error) {
	row := q.db.QueryRowContext(ctx, addCricketBatsScore,
		arg.BatsmanID,
		arg.MatchID,
		arg.TeamID,
		arg.Position,
		arg.RunsScored,
		arg.BallsFaced,
		arg.Fours,
		arg.Sixes,
	)
	var i Bat
	err := row.Scan(
		&i.ID,
		&i.BatsmanID,
		&i.TeamID,
		&i.MatchID,
		&i.Position,
		&i.RunsScored,
		&i.BallsFaced,
		&i.Fours,
		&i.Sixes,
	)
	return i, err
}

const addCricketWickets = `-- name: AddCricketWickets :one
INSERT INTO wickets (
    match_id,
    team_id,
    batsman_id,
    bowler_id,
    wickets_number,
    wicket_type
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, match_id, team_id, batsman_id, bowler_id, wickets_number, wicket_type
`

type AddCricketWicketsParams struct {
	MatchID       int64  `json:"match_id"`
	TeamID        int64  `json:"team_id"`
	BatsmanID     int64  `json:"batsman_id"`
	BowlerID      int64  `json:"bowler_id"`
	WicketsNumber int32  `json:"wickets_number"`
	WicketType    string `json:"wicket_type"`
}

func (q *Queries) AddCricketWickets(ctx context.Context, arg AddCricketWicketsParams) (Wicket, error) {
	row := q.db.QueryRowContext(ctx, addCricketWickets,
		arg.MatchID,
		arg.TeamID,
		arg.BatsmanID,
		arg.BowlerID,
		arg.WicketsNumber,
		arg.WicketType,
	)
	var i Wicket
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.BatsmanID,
		&i.BowlerID,
		&i.WicketsNumber,
		&i.WicketType,
	)
	return i, err
}

const getCricketBall = `-- name: GetCricketBall :one
SELECT id, team_id, match_id, bowler_id, ball, runs, wickets, wide, no_ball FROM balls
WHERE match_id=$1 AND bowler_id=$2 LIMIT 1
`

type GetCricketBallParams struct {
	MatchID  int64 `json:"match_id"`
	BowlerID int64 `json:"bowler_id"`
}

func (q *Queries) GetCricketBall(ctx context.Context, arg GetCricketBallParams) (Ball, error) {
	row := q.db.QueryRowContext(ctx, getCricketBall, arg.MatchID, arg.BowlerID)
	var i Ball
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MatchID,
		&i.BowlerID,
		&i.Ball,
		&i.Runs,
		&i.Wickets,
		&i.Wide,
		&i.NoBall,
	)
	return i, err
}

const getCricketBalls = `-- name: GetCricketBalls :many
SELECT id, team_id, match_id, bowler_id, ball, runs, wickets, wide, no_ball FROM balls
WHERE match_id=$1 AND team_id=$2
`

type GetCricketBallsParams struct {
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) GetCricketBalls(ctx context.Context, arg GetCricketBallsParams) ([]Ball, error) {
	rows, err := q.db.QueryContext(ctx, getCricketBalls, arg.MatchID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ball
	for rows.Next() {
		var i Ball
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.MatchID,
			&i.BowlerID,
			&i.Ball,
			&i.Runs,
			&i.Wickets,
			&i.Wide,
			&i.NoBall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCricketPlayerScore = `-- name: GetCricketPlayerScore :one
SELECT id, batsman_id, team_id, match_id, position, runs_scored, balls_faced, fours, sixes FROM bats
WHERE match_id=$1 AND batsman_id=$2 LIMIT 1
`

type GetCricketPlayerScoreParams struct {
	MatchID   int64 `json:"match_id"`
	BatsmanID int64 `json:"batsman_id"`
}

func (q *Queries) GetCricketPlayerScore(ctx context.Context, arg GetCricketPlayerScoreParams) (Bat, error) {
	row := q.db.QueryRowContext(ctx, getCricketPlayerScore, arg.MatchID, arg.BatsmanID)
	var i Bat
	err := row.Scan(
		&i.ID,
		&i.BatsmanID,
		&i.TeamID,
		&i.MatchID,
		&i.Position,
		&i.RunsScored,
		&i.BallsFaced,
		&i.Fours,
		&i.Sixes,
	)
	return i, err
}

const getCricketPlayersScore = `-- name: GetCricketPlayersScore :many
SELECT id, batsman_id, team_id, match_id, position, runs_scored, balls_faced, fours, sixes FROM bats
WHERE match_id=$1 AND team_id=$2
ORDER BY position
`

type GetCricketPlayersScoreParams struct {
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) GetCricketPlayersScore(ctx context.Context, arg GetCricketPlayersScoreParams) ([]Bat, error) {
	rows, err := q.db.QueryContext(ctx, getCricketPlayersScore, arg.MatchID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bat
	for rows.Next() {
		var i Bat
		if err := rows.Scan(
			&i.ID,
			&i.BatsmanID,
			&i.TeamID,
			&i.MatchID,
			&i.Position,
			&i.RunsScored,
			&i.BallsFaced,
			&i.Fours,
			&i.Sixes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCricketWicket = `-- name: GetCricketWicket :one
SELECT id, match_id, team_id, batsman_id, bowler_id, wickets_number, wicket_type FROM wickets
WHERE match_id=$1 AND batsman_id=$2 LIMIT 1
`

type GetCricketWicketParams struct {
	MatchID   int64 `json:"match_id"`
	BatsmanID int64 `json:"batsman_id"`
}

func (q *Queries) GetCricketWicket(ctx context.Context, arg GetCricketWicketParams) (Wicket, error) {
	row := q.db.QueryRowContext(ctx, getCricketWicket, arg.MatchID, arg.BatsmanID)
	var i Wicket
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.BatsmanID,
		&i.BowlerID,
		&i.WicketsNumber,
		&i.WicketType,
	)
	return i, err
}

const getCricketWickets = `-- name: GetCricketWickets :many
SELECT id, match_id, team_id, batsman_id, bowler_id, wickets_number, wicket_type FROM wickets
WHERE match_id=$1 AND team_id=$2
`

type GetCricketWicketsParams struct {
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) GetCricketWickets(ctx context.Context, arg GetCricketWicketsParams) ([]Wicket, error) {
	rows, err := q.db.QueryContext(ctx, getCricketWickets, arg.MatchID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wicket
	for rows.Next() {
		var i Wicket
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.TeamID,
			&i.BatsmanID,
			&i.BowlerID,
			&i.WicketsNumber,
			&i.WicketType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCricketBowler = `-- name: UpdateCricketBowler :one
UPDATE balls
SET 
    ball = $1,
    runs = runs + $2,
    wickets = wickets + $3,
    wide = wide + $4,
    no_ball = no_ball + $5
WHERE match_id = $6 AND bowler_id = $7 AND team_id=$8
RETURNING id, team_id, match_id, bowler_id, ball, runs, wickets, wide, no_ball
`

type UpdateCricketBowlerParams struct {
	Ball     int32 `json:"ball"`
	Runs     int32 `json:"runs"`
	Wickets  int32 `json:"wickets"`
	Wide     int32 `json:"wide"`
	NoBall   int32 `json:"no_ball"`
	MatchID  int64 `json:"match_id"`
	BowlerID int64 `json:"bowler_id"`
	TeamID   int64 `json:"team_id"`
}

func (q *Queries) UpdateCricketBowler(ctx context.Context, arg UpdateCricketBowlerParams) (Ball, error) {
	row := q.db.QueryRowContext(ctx, updateCricketBowler,
		arg.Ball,
		arg.Runs,
		arg.Wickets,
		arg.Wide,
		arg.NoBall,
		arg.MatchID,
		arg.BowlerID,
		arg.TeamID,
	)
	var i Ball
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MatchID,
		&i.BowlerID,
		&i.Ball,
		&i.Runs,
		&i.Wickets,
		&i.Wide,
		&i.NoBall,
	)
	return i, err
}

const updateCricketRunsScored = `-- name: UpdateCricketRunsScored :one
UPDATE bats
SET runs_scored = runs_scored + $1,
    balls_faced = balls_faced + $2,
    fours = fours + $3,
    sixes = sixes + $4
WHERE match_id = $5 AND batsman_id = $6 AND team_id=$7
RETURNING id, batsman_id, team_id, match_id, position, runs_scored, balls_faced, fours, sixes
`

type UpdateCricketRunsScoredParams struct {
	RunsScored int32 `json:"runs_scored"`
	BallsFaced int32 `json:"balls_faced"`
	Fours      int32 `json:"fours"`
	Sixes      int32 `json:"sixes"`
	MatchID    int64 `json:"match_id"`
	BatsmanID  int64 `json:"batsman_id"`
	TeamID     int64 `json:"team_id"`
}

func (q *Queries) UpdateCricketRunsScored(ctx context.Context, arg UpdateCricketRunsScoredParams) (Bat, error) {
	row := q.db.QueryRowContext(ctx, updateCricketRunsScored,
		arg.RunsScored,
		arg.BallsFaced,
		arg.Fours,
		arg.Sixes,
		arg.MatchID,
		arg.BatsmanID,
		arg.TeamID,
	)
	var i Bat
	err := row.Scan(
		&i.ID,
		&i.BatsmanID,
		&i.TeamID,
		&i.MatchID,
		&i.Position,
		&i.RunsScored,
		&i.BallsFaced,
		&i.Fours,
		&i.Sixes,
	)
	return i, err
}
