// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: cricket_match_score.sql

package db

import (
	"context"
)

const createCricketMatchScore = `-- name: CreateCricketMatchScore :one
INSERT INTO cricket_match_score (
    match_id,
    tournament_id,
    team_id,
    score,
    wickets,
    overs,
    extras,
    innings
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, match_id, tournament_id, team_id, score, wickets, overs, extras, innings
`

type CreateCricketMatchScoreParams struct {
	MatchID      int64 `json:"match_id"`
	TournamentID int64 `json:"tournament_id"`
	TeamID       int64 `json:"team_id"`
	Score        int64 `json:"score"`
	Wickets      int64 `json:"wickets"`
	Overs        int64 `json:"overs"`
	Extras       int64 `json:"extras"`
	Innings      int64 `json:"innings"`
}

func (q *Queries) CreateCricketMatchScore(ctx context.Context, arg CreateCricketMatchScoreParams) (CricketMatchScore, error) {
	row := q.db.QueryRowContext(ctx, createCricketMatchScore,
		arg.MatchID,
		arg.TournamentID,
		arg.TeamID,
		arg.Score,
		arg.Wickets,
		arg.Overs,
		arg.Extras,
		arg.Innings,
	)
	var i CricketMatchScore
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TournamentID,
		&i.TeamID,
		&i.Score,
		&i.Wickets,
		&i.Overs,
		&i.Extras,
		&i.Innings,
	)
	return i, err
}

const getCricketMatchScore = `-- name: GetCricketMatchScore :one
SELECT id, match_id, tournament_id, team_id, score, wickets, overs, extras, innings FROM cricket_match_score
WHERE match_id=$1 AND team_id=$2
`

type GetCricketMatchScoreParams struct {
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) GetCricketMatchScore(ctx context.Context, arg GetCricketMatchScoreParams) (CricketMatchScore, error) {
	row := q.db.QueryRowContext(ctx, getCricketMatchScore, arg.MatchID, arg.TeamID)
	var i CricketMatchScore
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TournamentID,
		&i.TeamID,
		&i.Score,
		&i.Wickets,
		&i.Overs,
		&i.Extras,
		&i.Innings,
	)
	return i, err
}

const updateCricketMatchExtras = `-- name: UpdateCricketMatchExtras :one
UPDATE cricket_match_score
SET extras=$1
WHERE match_id=$2 AND team_id=$3
RETURNING id, match_id, tournament_id, team_id, score, wickets, overs, extras, innings
`

type UpdateCricketMatchExtrasParams struct {
	Extras  int64 `json:"extras"`
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) UpdateCricketMatchExtras(ctx context.Context, arg UpdateCricketMatchExtrasParams) (CricketMatchScore, error) {
	row := q.db.QueryRowContext(ctx, updateCricketMatchExtras, arg.Extras, arg.MatchID, arg.TeamID)
	var i CricketMatchScore
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TournamentID,
		&i.TeamID,
		&i.Score,
		&i.Wickets,
		&i.Overs,
		&i.Extras,
		&i.Innings,
	)
	return i, err
}

const updateCricketMatchInnings = `-- name: UpdateCricketMatchInnings :one
UPDATE cricket_match_score
SET innings=$1
WHERE match_id=$2 AND team_id=$3
RETURNING id, match_id, tournament_id, team_id, score, wickets, overs, extras, innings
`

type UpdateCricketMatchInningsParams struct {
	Innings int64 `json:"innings"`
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) UpdateCricketMatchInnings(ctx context.Context, arg UpdateCricketMatchInningsParams) (CricketMatchScore, error) {
	row := q.db.QueryRowContext(ctx, updateCricketMatchInnings, arg.Innings, arg.MatchID, arg.TeamID)
	var i CricketMatchScore
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TournamentID,
		&i.TeamID,
		&i.Score,
		&i.Wickets,
		&i.Overs,
		&i.Extras,
		&i.Innings,
	)
	return i, err
}

const updateCricketMatchRunsScore = `-- name: UpdateCricketMatchRunsScore :one
UPDATE cricket_match_score
SET score=$1
WHERE match_id=$2 AND team_id=$3
RETURNING id, match_id, tournament_id, team_id, score, wickets, overs, extras, innings
`

type UpdateCricketMatchRunsScoreParams struct {
	Score   int64 `json:"score"`
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) UpdateCricketMatchRunsScore(ctx context.Context, arg UpdateCricketMatchRunsScoreParams) (CricketMatchScore, error) {
	row := q.db.QueryRowContext(ctx, updateCricketMatchRunsScore, arg.Score, arg.MatchID, arg.TeamID)
	var i CricketMatchScore
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TournamentID,
		&i.TeamID,
		&i.Score,
		&i.Wickets,
		&i.Overs,
		&i.Extras,
		&i.Innings,
	)
	return i, err
}

const updateCricketMatchWickets = `-- name: UpdateCricketMatchWickets :one
UPDATE cricket_match_score
SET wickets=$1
WHERE match_id=$2 AND team_id=$3
RETURNING id, match_id, tournament_id, team_id, score, wickets, overs, extras, innings
`

type UpdateCricketMatchWicketsParams struct {
	Wickets int64 `json:"wickets"`
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) UpdateCricketMatchWickets(ctx context.Context, arg UpdateCricketMatchWicketsParams) (CricketMatchScore, error) {
	row := q.db.QueryRowContext(ctx, updateCricketMatchWickets, arg.Wickets, arg.MatchID, arg.TeamID)
	var i CricketMatchScore
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TournamentID,
		&i.TeamID,
		&i.Score,
		&i.Wickets,
		&i.Overs,
		&i.Extras,
		&i.Innings,
	)
	return i, err
}
