// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: football_substitution.sql

package db

import (
	"context"
)

const addFootballSubstitution = `-- name: AddFootballSubstitution :one
INSERT INTO football_substitution (
    team_id,
    player_id,
    match_id,
    position
) VALUES ( $1, $2, $3, $4 )
RETURNING id, team_id, player_id, match_id, position
`

type AddFootballSubstitutionParams struct {
	TeamID   int64  `json:"team_id"`
	PlayerID int64  `json:"player_id"`
	MatchID  int64  `json:"match_id"`
	Position string `json:"position"`
}

func (q *Queries) AddFootballSubstitution(ctx context.Context, arg AddFootballSubstitutionParams) (FootballSubstitution, error) {
	row := q.db.QueryRowContext(ctx, addFootballSubstitution,
		arg.TeamID,
		arg.PlayerID,
		arg.MatchID,
		arg.Position,
	)
	var i FootballSubstitution
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PlayerID,
		&i.MatchID,
		&i.Position,
	)
	return i, err
}

const getFootballSubstitution = `-- name: GetFootballSubstitution :many
SELECT id, team_id, player_id, match_id, position FROM football_substitution
WHERE match_id=$1 AND team_id=$2
`

type GetFootballSubstitutionParams struct {
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) GetFootballSubstitution(ctx context.Context, arg GetFootballSubstitutionParams) ([]FootballSubstitution, error) {
	rows, err := q.db.QueryContext(ctx, getFootballSubstitution, arg.MatchID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FootballSubstitution
	for rows.Next() {
		var i FootballSubstitution
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.PlayerID,
			&i.MatchID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
