// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: football_statistics.sql

package db

import (
	"context"
)

const createFootballStatistics = `-- name: CreateFootballStatistics :one
INSERT INTO football_statistics (
    match_id,
    team_id,
    shots_on_target,
    total_shots,
    corner_kicks,
    fouls,
    goalkeeper_saves,
    free_kicks,
    yellow_cards,
    red_cards
) VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, match_id, team_id, shots_on_target, total_shots, corner_kicks, fouls, goalkeeper_saves, free_kicks, yellow_cards, red_cards
`

type CreateFootballStatisticsParams struct {
	MatchID         int64 `json:"match_id"`
	TeamID          int64 `json:"team_id"`
	ShotsOnTarget   int32 `json:"shots_on_target"`
	TotalShots      int32 `json:"total_shots"`
	CornerKicks     int32 `json:"corner_kicks"`
	Fouls           int32 `json:"fouls"`
	GoalkeeperSaves int32 `json:"goalkeeper_saves"`
	FreeKicks       int32 `json:"free_kicks"`
	YellowCards     int32 `json:"yellow_cards"`
	RedCards        int32 `json:"red_cards"`
}

func (q *Queries) CreateFootballStatistics(ctx context.Context, arg CreateFootballStatisticsParams) (FootballStatistic, error) {
	row := q.db.QueryRowContext(ctx, createFootballStatistics,
		arg.MatchID,
		arg.TeamID,
		arg.ShotsOnTarget,
		arg.TotalShots,
		arg.CornerKicks,
		arg.Fouls,
		arg.GoalkeeperSaves,
		arg.FreeKicks,
		arg.YellowCards,
		arg.RedCards,
	)
	var i FootballStatistic
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.ShotsOnTarget,
		&i.TotalShots,
		&i.CornerKicks,
		&i.Fouls,
		&i.GoalkeeperSaves,
		&i.FreeKicks,
		&i.YellowCards,
		&i.RedCards,
	)
	return i, err
}

const getFootballStatistics = `-- name: GetFootballStatistics :one
SELECT id, match_id, team_id, shots_on_target, total_shots, corner_kicks, fouls, goalkeeper_saves, free_kicks, yellow_cards, red_cards FROM football_statistics
WHERE match_id=$1 AND team_id=$2
`

type GetFootballStatisticsParams struct {
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) GetFootballStatistics(ctx context.Context, arg GetFootballStatisticsParams) (FootballStatistic, error) {
	row := q.db.QueryRowContext(ctx, getFootballStatistics, arg.MatchID, arg.TeamID)
	var i FootballStatistic
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.ShotsOnTarget,
		&i.TotalShots,
		&i.CornerKicks,
		&i.Fouls,
		&i.GoalkeeperSaves,
		&i.FreeKicks,
		&i.YellowCards,
		&i.RedCards,
	)
	return i, err
}

const updateFootballStatistics = `-- name: UpdateFootballStatistics :one
UPDATE football_statistics
SET 
    shots_on_target = CASE WHEN $1 IS NOT NULL THEN shots_on_target + $1 ELSE 0 END,
    total_shots = CASE WHEN $2 IS NOT NULL THEN total_shots + $2 ELSE 0 END,
    corner_kicks = CASE WHEN $3 IS NOT NULL THEN corner_kicks + $3 ELSE 0 END,
    fouls = CASE WHEN $4 IS NOT NULL THEN fouls + $4 ELSE fouls END,
    goalkeeper_saves = CASE WHEN $5 IS NOT NULL THEN goalkeeper_saves + $5 ELSE 0 END,
    free_kicks = CASE WHEN $6 IS NOT NULL THEN free_kicks + $6 ELSE 0 END,
    yellow_cards = CASE WHEN $7 IS NOT NULL THEN yellow_cards + $7 ELSE 0 END,
    red_cards = CASE WHEN $8 IS NOT NULL THEN red_cards + $8 ELSE 0 END
WHERE match_id = $9 AND team_id = $10
RETURNING id, match_id, team_id, shots_on_target, total_shots, corner_kicks, fouls, goalkeeper_saves, free_kicks, yellow_cards, red_cards
`

type UpdateFootballStatisticsParams struct {
	ShotsOnTarget   int32 `json:"shots_on_target"`
	TotalShots      int32 `json:"total_shots"`
	CornerKicks     int32 `json:"corner_kicks"`
	Fouls           int32 `json:"fouls"`
	GoalkeeperSaves int32 `json:"goalkeeper_saves"`
	FreeKicks       int32 `json:"free_kicks"`
	YellowCards     int32 `json:"yellow_cards"`
	RedCards        int32 `json:"red_cards"`
	MatchID         int64 `json:"match_id"`
	TeamID          int64 `json:"team_id"`
}

func (q *Queries) UpdateFootballStatistics(ctx context.Context, arg UpdateFootballStatisticsParams) (FootballStatistic, error) {
	row := q.db.QueryRowContext(ctx, updateFootballStatistics,
		arg.ShotsOnTarget,
		arg.TotalShots,
		arg.CornerKicks,
		arg.Fouls,
		arg.GoalkeeperSaves,
		arg.FreeKicks,
		arg.YellowCards,
		arg.RedCards,
		arg.MatchID,
		arg.TeamID,
	)
	var i FootballStatistic
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.ShotsOnTarget,
		&i.TotalShots,
		&i.CornerKicks,
		&i.Fouls,
		&i.GoalkeeperSaves,
		&i.FreeKicks,
		&i.YellowCards,
		&i.RedCards,
	)
	return i, err
}
