// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: football_penalty_shootout.sql

package db

import (
	"context"
)

const addFootballPenaltyShootout = `-- name: AddFootballPenaltyShootout :one
INSERT INTO penalty_shootout (
    match_id,
    team_id,
    player_id,
    scored
) VALUES ($1, $2, $3, $4)
RETURNING id, match_id, team_id, player_id, scored
`

type AddFootballPenaltyShootoutParams struct {
	MatchID  int64 `json:"match_id"`
	TeamID   int64 `json:"team_id"`
	PlayerID int64 `json:"player_id"`
	Scored   bool  `json:"scored"`
}

func (q *Queries) AddFootballPenaltyShootout(ctx context.Context, arg AddFootballPenaltyShootoutParams) (PenaltyShootout, error) {
	row := q.db.QueryRowContext(ctx, addFootballPenaltyShootout,
		arg.MatchID,
		arg.TeamID,
		arg.PlayerID,
		arg.Scored,
	)
	var i PenaltyShootout
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.PlayerID,
		&i.Scored,
	)
	return i, err
}

const getFootballPenaltyShootout = `-- name: GetFootballPenaltyShootout :many
SELECT id, match_id, team_id, player_id, scored FROM penalty_shootout
WHERE match_id=$1 AND team_id=$2
ORDER BY id DESC
`

type GetFootballPenaltyShootoutParams struct {
	MatchID int64 `json:"match_id"`
	TeamID  int64 `json:"team_id"`
}

func (q *Queries) GetFootballPenaltyShootout(ctx context.Context, arg GetFootballPenaltyShootoutParams) ([]PenaltyShootout, error) {
	rows, err := q.db.QueryContext(ctx, getFootballPenaltyShootout, arg.MatchID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyShootout
	for rows.Next() {
		var i PenaltyShootout
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.TeamID,
			&i.PlayerID,
			&i.Scored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFootballPenaltyShootout = `-- name: UpdateFootballPenaltyShootout :one
UPDATE penalty_shootout
SET scored = scored + $1
WHERE id=$2
RETURNING id, match_id, team_id, player_id, scored
`

type UpdateFootballPenaltyShootoutParams struct {
	Scored bool  `json:"scored"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateFootballPenaltyShootout(ctx context.Context, arg UpdateFootballPenaltyShootoutParams) (PenaltyShootout, error) {
	row := q.db.QueryRowContext(ctx, updateFootballPenaltyShootout, arg.Scored, arg.ID)
	var i PenaltyShootout
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.PlayerID,
		&i.Scored,
	)
	return i, err
}
