// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: friends.sql

package db

import (
	"context"
	"database/sql"
)

const createFriends = `-- name: CreateFriends :one
INSERT INTO friends (
    friend_name,
    friend_username
) VALUES (
    $1, $2
) RETURNING id, friend_username, friend_name
`

type CreateFriendsParams struct {
	FriendName     sql.NullString `json:"friend_name"`
	FriendUsername sql.NullString `json:"friend_username"`
}

func (q *Queries) CreateFriends(ctx context.Context, arg CreateFriendsParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, createFriends, arg.FriendName, arg.FriendUsername)
	var i Friend
	err := row.Scan(&i.ID, &i.FriendUsername, &i.FriendName)
	return i, err
}

const getFriends = `-- name: GetFriends :one
SELECT id, friend_username, friend_name FROM friends
WHERE friend_username = $1
`

func (q *Queries) GetFriends(ctx context.Context, friendUsername sql.NullString) (Friend, error) {
	row := q.db.QueryRowContext(ctx, getFriends, friendUsername)
	var i Friend
	err := row.Scan(&i.ID, &i.FriendUsername, &i.FriendName)
	return i, err
}

const getListFriends = `-- name: GetListFriends :many
SELECT id, friend_username, friend_name FROM friends
ORDER BY id
`

func (q *Queries) GetListFriends(ctx context.Context) ([]Friend, error) {
	rows, err := q.db.QueryContext(ctx, getListFriends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friend
	for rows.Next() {
		var i Friend
		if err := rows.Scan(&i.ID, &i.FriendUsername, &i.FriendName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
