// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: likeThread.sql

package db

import (
	"context"
)

const countLikeUser = `-- name: CountLikeUser :one
SELECT COUNT(*) FROM like_thread
WHERE thread_id = $1
`

func (q *Queries) CountLikeUser(ctx context.Context, threadID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLikeUser, threadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLike = `-- name: CreateLike :one
INSERT INTO like_thread (
    thread_id,
    username
) VALUES (
  $1, $2
) RETURNING id, thread_id, username
`

type CreateLikeParams struct {
	ThreadID int64  `json:"thread_id"`
	Username string `json:"username"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (LikeThread, error) {
	row := q.db.QueryRowContext(ctx, createLike, arg.ThreadID, arg.Username)
	var i LikeThread
	err := row.Scan(&i.ID, &i.ThreadID, &i.Username)
	return i, err
}

const getLike = `-- name: GetLike :one
SELECT id, thread_id, username FROM like_thread
WHERE username = $1 LIMIT $1
`

func (q *Queries) GetLike(ctx context.Context, limit int32) (LikeThread, error) {
	row := q.db.QueryRowContext(ctx, getLike, limit)
	var i LikeThread
	err := row.Scan(&i.ID, &i.ThreadID, &i.Username)
	return i, err
}

const userListLike = `-- name: UserListLike :many
SELECT id, thread_id, username FROM like_thread
ORDER BY username
`

func (q *Queries) UserListLike(ctx context.Context) ([]LikeThread, error) {
	rows, err := q.db.QueryContext(ctx, userListLike)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LikeThread
	for rows.Next() {
		var i LikeThread
		if err := rows.Scan(&i.ID, &i.ThreadID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
