// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: login.sql

package db

import (
	"context"
)

const login = `-- name: login :one
INSERT INTO login (
    username,
    password
) VALUES (
    $1, $2
) RETURNING username, password
`

type loginParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) login(ctx context.Context, arg loginParams) (Login, error) {
	row := q.db.QueryRowContext(ctx, login, arg.Username, arg.Password)
	var i Login
	err := row.Scan(&i.Username, &i.Password)
	return i, err
}
