// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Community struct {
	ID              int64     `json:"id"`
	Owner           string    `json:"owner"`
	CommunitiesName string    `json:"communities_name"`
	Description     string    `json:"description"`
	CommunityType   string    `json:"community_type"`
	CreatedAt       time.Time `json:"created_at"`
}

type Friend struct {
	ID             int64  `json:"id"`
	Owner          string `json:"owner"`
	FriendUsername string `json:"friend_username"`
}

type FriendsRequest struct {
	ID               int64     `json:"id"`
	SenderUsername   string    `json:"sender_username"`
	RecieverUsername string    `json:"reciever_username"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Signup struct {
	MobileNumber string `json:"mobile_number"`
	Otp          string `json:"otp"`
}

type Thread struct {
	ID              int64          `json:"id"`
	Username        string         `json:"username"`
	CommunitiesName sql.NullString `json:"communities_name"`
	Title           sql.NullString `json:"title"`
	Content         sql.NullString `json:"content"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	Username       string    `json:"username"`
	MobileNumber   string    `json:"mobile_number"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
