// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: organizer.sql

package db

import (
	"context"
)

const createOrganizer = `-- name: CreateOrganizer :one
INSERT INTO organizer (
    organizer_name,
    tournament_id
) VALUES ($1, $2) RETURNING organizer_id, organizer_name, tournament_id
`

type CreateOrganizerParams struct {
	OrganizerName string `json:"organizer_name"`
	TournamentID  int64  `json:"tournament_id"`
}

func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (Organizer, error) {
	row := q.db.QueryRowContext(ctx, createOrganizer, arg.OrganizerName, arg.TournamentID)
	var i Organizer
	err := row.Scan(&i.OrganizerID, &i.OrganizerName, &i.TournamentID)
	return i, err
}

const getOrganizer = `-- name: GetOrganizer :many
SELECT organizer_id, organizer_name, tournament_id FROM organizer
WHERE tournament_id=$1
`

func (q *Queries) GetOrganizer(ctx context.Context, tournamentID int64) ([]Organizer, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizer, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organizer
	for rows.Next() {
		var i Organizer
		if err := rows.Scan(&i.OrganizerID, &i.OrganizerName, &i.TournamentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
