// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: player.sql

package db

import (
	"context"
)

const getPlayer = `-- name: GetPlayer :one
SELECT id, name, slug, short_name, media_url, positions, sports, country FROM players
WHERE id=$1
`

func (q *Queries) GetPlayer(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.MediaUrl,
		&i.Positions,
		&i.Sports,
		&i.Country,
	)
	return i, err
}

const getPlayersCountry = `-- name: GetPlayersCountry :many
SELECT id, name, slug, short_name, media_url, positions, sports, country FROM players
WHERE country=$1
`

func (q *Queries) GetPlayersCountry(ctx context.Context, country string) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersCountry, country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ShortName,
			&i.MediaUrl,
			&i.Positions,
			&i.Sports,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newPlayer = `-- name: NewPlayer :one
INSERT INTO players (
    name,
    slug,
    short_name,
    media_url,
    positions,
    sports,
    country
) VALUES ($1, $2, $3, $4, $5, $6, $7 ) RETURNING id, name, slug, short_name, media_url, positions, sports, country
`

type NewPlayerParams struct {
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	ShortName string `json:"short_name"`
	MediaUrl  string `json:"media_url"`
	Positions string `json:"positions"`
	Sports    string `json:"sports"`
	Country   string `json:"country"`
}

func (q *Queries) NewPlayer(ctx context.Context, arg NewPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, newPlayer,
		arg.Name,
		arg.Slug,
		arg.ShortName,
		arg.MediaUrl,
		arg.Positions,
		arg.Sports,
		arg.Country,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.MediaUrl,
		&i.Positions,
		&i.Sports,
		&i.Country,
	)
	return i, err
}

const searchPlayer = `-- name: SearchPlayer :many
SELECT id, name, slug, short_name, media_url, positions, sports, country FROM players
WHERE name LIKE $1
`

func (q *Queries) SearchPlayer(ctx context.Context, name string) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, searchPlayer, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ShortName,
			&i.MediaUrl,
			&i.Positions,
			&i.Sports,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerMedia = `-- name: UpdatePlayerMedia :one
UPDATE players
SET media_url=$1
WHERE id=$2
RETURNING id, name, slug, short_name, media_url, positions, sports, country
`

type UpdatePlayerMediaParams struct {
	MediaUrl string `json:"media_url"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdatePlayerMedia(ctx context.Context, arg UpdatePlayerMediaParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerMedia, arg.MediaUrl, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.MediaUrl,
		&i.Positions,
		&i.Sports,
		&i.Country,
	)
	return i, err
}

const updatePlayerPosition = `-- name: UpdatePlayerPosition :one
UPDATE players
SET positions=$1
WHERE id=$2
RETURNING id, name, slug, short_name, media_url, positions, sports, country
`

type UpdatePlayerPositionParams struct {
	Positions string `json:"positions"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdatePlayerPosition(ctx context.Context, arg UpdatePlayerPositionParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerPosition, arg.Positions, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.MediaUrl,
		&i.Positions,
		&i.Sports,
		&i.Country,
	)
	return i, err
}
