// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: searchUsers.sql

package db

import (
	"context"
)

const createSearchUser = `-- name: CreateSearchUser :one
INSERT INTO searchusers (
    username
) VALUES (
     $1
) RETURNING username
`

func (q *Queries) CreateSearchUser(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, createSearchUser, username)
	err := row.Scan(&username)
	return username, err
}
