// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: searchBar.sql

package db

import (
	"context"
	"database/sql"
)

const getSearchBar = `-- name: getSearchBar :many
SELECT full_name, username, communities FROM search_bar
WHERE (full_name ILIKE '%' || $1 || '%') | (username ILIKE '%' || $1 || '%') | (communities ILIKE '%' || $1 || '%')
`

func (q *Queries) getSearchBar(ctx context.Context, dollar_1 sql.NullString) ([]SearchBar, error) {
	rows, err := q.db.QueryContext(ctx, getSearchBar, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBar
	for rows.Next() {
		var i SearchBar
		if err := rows.Scan(&i.FullName, &i.Username, &i.Communities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
