// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: threads.sql

package db

import (
	"context"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
    username,
    communities_name,
    title,
    content,
    media_type,
    media_url,
    like_count
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
) RETURNING id, username, communities_name, title, content, media_type, media_url, like_count, created_at
`

type CreateThreadParams struct {
	Username        string `json:"username"`
	CommunitiesName string `json:"communities_name"`
	Title           string `json:"title"`
	Content         string `json:"content"`
	MediaType       string `json:"media_type"`
	MediaUrl        string `json:"media_url"`
	LikeCount       int64  `json:"like_count"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, createThread,
		arg.Username,
		arg.CommunitiesName,
		arg.Title,
		arg.Content,
		arg.MediaType,
		arg.MediaUrl,
		arg.LikeCount,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CommunitiesName,
		&i.Title,
		&i.Content,
		&i.MediaType,
		&i.MediaUrl,
		&i.LikeCount,
		&i.CreatedAt,
	)
	return i, err
}

const getAllThreads = `-- name: GetAllThreads :many
SELECT id, username, communities_name, title, content, media_type, media_url, like_count, created_at FROM threads
`

func (q *Queries) GetAllThreads(ctx context.Context) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, getAllThreads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CommunitiesName,
			&i.Title,
			&i.Content,
			&i.MediaType,
			&i.MediaUrl,
			&i.LikeCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllThreadsByCommunities = `-- name: GetAllThreadsByCommunities :many
SELECT id, username, communities_name, title, content, media_type, media_url, like_count, created_at FROM threads
WHERE communities_name = $1
ORDER BY id=$1
`

func (q *Queries) GetAllThreadsByCommunities(ctx context.Context, communitiesName string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, getAllThreadsByCommunities, communitiesName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CommunitiesName,
			&i.Title,
			&i.Content,
			&i.MediaType,
			&i.MediaUrl,
			&i.LikeCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThread = `-- name: GetThread :one
SELECT id, username, communities_name, title, content, media_type, media_url, like_count, created_at FROM threads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetThread(ctx context.Context, id int64) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CommunitiesName,
		&i.Title,
		&i.Content,
		&i.MediaType,
		&i.MediaUrl,
		&i.LikeCount,
		&i.CreatedAt,
	)
	return i, err
}

const updateThreadLike = `-- name: UpdateThreadLike :one
UPDATE threads
SET like_count=like_count + 1
WHERE id=$1
RETURNING id, username, communities_name, title, content, media_type, media_url, like_count, created_at
`

func (q *Queries) UpdateThreadLike(ctx context.Context, id int64) (Thread, error) {
	row := q.db.QueryRowContext(ctx, updateThreadLike, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CommunitiesName,
		&i.Title,
		&i.Content,
		&i.MediaType,
		&i.MediaUrl,
		&i.LikeCount,
		&i.CreatedAt,
	)
	return i, err
}
