// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: tournament_team.sql

package db

import (
	"context"
	"database/sql"
)

const getTournamentTeam = `-- name: GetTournamentTeam :one
SELECT tournament_id, team_id FROM tournament_team
WHERE team_id=$1
`

func (q *Queries) GetTournamentTeam(ctx context.Context, teamID int64) (TournamentTeam, error) {
	row := q.db.QueryRowContext(ctx, getTournamentTeam, teamID)
	var i TournamentTeam
	err := row.Scan(&i.TournamentID, &i.TeamID)
	return i, err
}

const getTournamentTeams = `-- name: GetTournamentTeams :many
SELECT 
    tm.id,
    tm.name,
    tm.admin,
    tm.slug,
    tm.shortname,
    tm.country,
    tm.media_url,
    tm.type,
    tm.gender,
    tm.national,
    tm.sports 
FROM tournament_team tt
LEFT JOIN teams AS tm ON tm.id == tt.team_id
WHERE tournament_id=$1
`

type GetTournamentTeamsRow struct {
	ID        sql.NullInt64  `json:"id"`
	Name      sql.NullString `json:"name"`
	Admin     sql.NullString `json:"admin"`
	Slug      sql.NullString `json:"slug"`
	Shortname sql.NullString `json:"shortname"`
	Country   sql.NullString `json:"country"`
	MediaUrl  sql.NullString `json:"media_url"`
	Type      sql.NullString `json:"type"`
	Gender    sql.NullString `json:"gender"`
	National  sql.NullBool   `json:"national"`
	Sports    sql.NullString `json:"sports"`
}

func (q *Queries) GetTournamentTeams(ctx context.Context, tournamentID int64) ([]GetTournamentTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentTeams, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTournamentTeamsRow
	for rows.Next() {
		var i GetTournamentTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Admin,
			&i.Slug,
			&i.Shortname,
			&i.Country,
			&i.MediaUrl,
			&i.Type,
			&i.Gender,
			&i.National,
			&i.Sports,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournamentTeamsCount = `-- name: GetTournamentTeamsCount :one

SELECT COUNT(*) FROM tournament_team
WHERE tournament_id=$1
`

// -- name: GetTournamentTeams :many
// SELECT * FROM tournament_team
// WHERE tournament_id=$1;
func (q *Queries) GetTournamentTeamsCount(ctx context.Context, tournamentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTournamentTeamsCount, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const newTournamentTeam = `-- name: NewTournamentTeam :one
INSERT INTO tournament_team (
    tournament_id,
    team_id
) VALUES ( $1, $2 )
RETURNING tournament_id, team_id
`

type NewTournamentTeamParams struct {
	TournamentID int64 `json:"tournament_id"`
	TeamID       int64 `json:"team_id"`
}

func (q *Queries) NewTournamentTeam(ctx context.Context, arg NewTournamentTeamParams) (TournamentTeam, error) {
	row := q.db.QueryRowContext(ctx, newTournamentTeam, arg.TournamentID, arg.TeamID)
	var i TournamentTeam
	err := row.Scan(&i.TournamentID, &i.TeamID)
	return i, err
}
