// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  mobile_number
) VALUES (
  $1, $2
) RETURNING username, mobile_number, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	MobileNumber string `json:"mobile_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.MobileNumber)
	var i User
	err := row.Scan(&i.Username, &i.MobileNumber, &i.CreatedAt)
	return i, err
}
