// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  mobile_number,
  hashed_password,
  role
) VALUES (
  $1, $2, $3, $4
) RETURNING username, mobile_number, hashed_password, role, id
`

type CreateUserParams struct {
	Username       string `json:"username"`
	MobileNumber   string `json:"mobile_number"`
	HashedPassword string `json:"hashed_password"`
	Role           string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.MobileNumber,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.MobileNumber,
		&i.HashedPassword,
		&i.Role,
		&i.ID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, mobile_number, hashed_password, role, id FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.MobileNumber,
		&i.HashedPassword,
		&i.Role,
		&i.ID,
	)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT DISTINCT username, mobile_number, hashed_password, role, id FROM users
WHERE username = $1
ORDER BY username
LIMIT $2
OFFSET $3
`

type ListUserParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListUser(ctx context.Context, arg ListUserParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUser, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Username,
			&i.MobileNumber,
			&i.HashedPassword,
			&i.Role,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
